name: Push To Firebase-DEV
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN_DEV }}
          PROJECT_PATH: firebase.json